name: lume-lcls-cu-inj-nn
channels:
  - conda-forge
dependencies:
  - prefect<2.0 # until lume-services registered with conda
  - docker-py>=5.0  # until lume-services registered with conda
  - tensorflow
  - keras
  - lume-model>=1.6.0
  - pydantic==1.10.9
  - botorch>=0.8.2
  - ipywidgets
  - tqdm
  - matplotlib
  - jupyterlab
  - ipykernel
  - jupyter
  - nb_conda_kernels
  - pip 
  - pip: 
    - git+https://github.com/singh96aman/lume-services.git@main
