name: lume-lcls-cu-inj-nn
channels:
  - conda-forge
dependencies:
  - prefect # until lume-services registered with conda
  - docker-py>=5.0 # until lume-services registered with conda
  - tensorflow
  - keras
  - pydantic
  - botorch>=0.8.2
  - ipywidgets
  - tqdm
  - matplotlib
  - jupyterlab
  - ipykernel
  - jupyter
  - nb_conda_kernels
  - pip 
  - pip: 
    - git+https://github.com/slaclab/lume-model.git
    - git+https://github.com/jbellister-slac/lume-services.git@prefect_2
