input_variables:
  distgen:r_dist:sigma_xy:value:
    pvname: IRIS:LR20:130:CONFG_SEL
    protocol: ca
    serve: false

  distgen:total_charge:value:
    pvname: BPMS:IN20:221:TMIT
    protocol: ca 
    serve: false

  distgen:t_dist:length:value: 
    pvname: distgen:t_dist:length:value
    protocol: ca 
    serve: true

  SOL1:solenoid_field_scale:
    pvname: SOLN:IN20:121:BACT
    protocol: ca
    serve: false

  CQ01:b1_gradient:
    pvname: QUAD:IN20:121:BACT
    protocol: ca
    serve: false

  SQ01:b1_gradient:
    pvname: QUAD:IN20:122:BACT
    protocol: ca
    serve: false

  L0A_phase:dtheta0_deg:
    pvname: ACCL:IN20:300:L0A_PDES
    protocol: ca
    serve: false

  L0B_phase:dtheta0_deg:
    pvname: ACCL:IN20:400:L0B_PDES
    protocol: ca
    serve: false

  L0A_scale:voltage:
    pvname: ACCL:IN20:300:L0A_ADES
    protocol: ca
    serve: false

  end_mean_z:
    pvname: end_mean_z
    protocol: ca
    serve: True

output_variables:
  output:
    pvname: OUTPUT
    protocol: pva
    fields: 
      - sigma_x
      - sigma_y
      - sigma_z
      - norm_emit_x
      - norm_emit_y